### PR TITLE
Fix computed-property.override deprecation

### LINKED ISSUE #235: Deprecation with Ember@3.9
After upgrading the app which is using ember-file-upload I'm getting this deprecation:
`computed-property.override`
`file-upload#for computed property was just overriden`
Need to fix it here: https://github.com/adopted-ember-addons/ember-file-upload/blob/05f734cb1e7126efb460bdbdfa49b8135511219d/addon/components/file-upload/component.js#L91
Probably we can use init() instead of computed property to fix that.

### PR DESCRIPTION
**Pull request by andreyfel**
Ember@3.9 deprecates overriding a computed property with .set().

Use didReceiveAttrs() hook to set the default value of the "for" property instead of using a computed property.

Fixes #235

### CODE REVIEW

File: addon/components/file-upload/component.js [hunk 1]
```diff
@@ -88,11 +88,7 @@ const component = Component.extend({
 
   attributeBindings: ['for'],
 
-  for: computed({
-    get() {
-      return `file-input-${uuid.short()}`;
-    }
-  }),
+  for: undefined,
```
Comment (Alonski) [inline addon/components/file-upload/component.js]: After looking at this again. Would it not be possible to have a setter for this computed prop instead of setting it in didReceiveAttrs?
Would that work?

Comment (andreyfel) [reply addon/components/file-upload/component.js]: Sure, we can use that approach as well. Changed the code to use setter.
